### PR TITLE
GSSoC: Implement User Authentication Routes and Model with Zod Validation #89

### PR DESCRIPTION
**Pull request by himanshuraimau**
#### Description:
This pull request adds user authentication routes and a user model with Zod validation to our backend project. The implementation includes signup and signin routes, password hashing, and environment variable setup.

#### Changes Made:
- Created a User model using Mongoose.
- Implemented signup and signin routes with Zod validation.
- Hashed passwords using bcrypt before saving to the database.
- Added necessary environment variables for JWT and bcrypt.
- Ensured proper error handling and response messages.

#### Tasks Completed:
1. Created User Model:
   - Defined a User schema with Mongoose.
   - Included fields for username, email, password, etc.
   - Added Zod validation for input fields.

2. Implemented Authentication Routes:
   - Created signup and signin routes.
   - Validated input using Zod.
   - Hashed passwords before saving to the database.
   - Returned appropriate responses for successful and failed authentication attempts.

3. Environment Variables:
   - Added environment variables for JWT secret and bcrypt salt rounds.

#### Proposed Solution:
- Utilized Mongoose for database modeling.
- Employed bcrypt for password hashing.
- Used JSON Web Tokens (JWT) for authentication.
- Employed Zod for input validation to ensure proper data formats and security.
- Revised the Readme file.

#### Additional Notes:
This pull request lays the foundation for user authentication in our backend application. Further enhancements and refinements may be required based on feedback and testing.

### Video:
[Screencast from 2024-05-31 00-39-39.webm](https://github.com/oxiton-foundation/click-metrics/assets/134522022/663fd266-b69e-44bc-9896-19322f4a5742)

#### Request for Review:
Please review the changes and provide feedback as necessary. Your input is valuable in ensuring the reliability and security of our authentication system.

Thank you!

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Resolve the conflicts!

**Comment by Swarnendu0123** [comment]
Remove `package.json` and user creation logic, as will will not follow this process to create users, we will use firebase for auth.

**Comment by himanshuraimau** [comment]
can i setup the setup? also can you merge this pull request i will change the further issues. 
thank you!

**Comment by Swarnendu0123** [comment]
As I couldn't review >1000 changes. I will appreciate it, if you create separate PR.

**Comment by himanshuraimau** [comment]
Ok let me see.
Actually I also got the git conflict the first time so I was kinda confused.

**Pull request closed without merging**
