### PR TITLE
loader added

### PR DESCRIPTION
**Pull request by Ansh101112**
### Feature Description

Added the required loader wherever possible and which increases the overall user experience as well. 

### Issue Fixed:
#49

### CODE REVIEW

**Comment by Ansh101112** [comment]
@Swarnendu0123 sir please view and merge it asap. Also add gssoc and level badge to this pr

**Comment by Swarnendu0123** [comment]
Attach screenshot.

**Comment by Ansh101112** [comment]
> Attach screenshots and videos.
Screenshot (155)
Here's the screenshot of the loader on loading the elements of home page.

**Comment by GitSentinel** [comment]
Attach a video of the loader working as well.

**Comment by Swarnendu0123** [comment]
Resolve conflicts and attach screenshots.

**Pull request closed without merging**
