### PR TITLE
New sections Added

### PR DESCRIPTION
**Pull request by Ansh101112**
### Description 
Added the new sections on home page and also add the required content to the site as well.

## Screenshots:
Screenshot (167)
Screenshot (168)

### Issue Fixed:
#99 

### Reviewers:
@Swarnendu0123 @GitSentinel

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Attach the light mode UI.

**Comment by Ansh101112** [comment]
Sir it is there when user choose to be in light mode then it will automatically converted into light mode.

**Comment by Ansh101112** [comment]
@GitSentinel @Swarnendu0123 sir please see this pr!!

**Comment by GitSentinel** [comment]
The dark mode contrast is not looking good. Also are there any light mode designs of the sections? Fix the colors of the dark mode so that there is contrast and it is easier for the visitors to navigate the website.

**Comment by Swarnendu0123** [comment]
Resolve the conflicts. When we are asking for attachment, attach the screenshot. We also know when we click on the light mode the the page will be in light mode.

**Pull request closed without merging**
