### PR TITLE
Adding shadow-hover-effect to the buttons

### PR DESCRIPTION
**Pull request by Sibam-Paul**
issue no #38 

Before clicking the default state of all the buttons
image
image

After hovering on it 
image
image
image

Please assign me and give necessary tags under GSsOC'24

### CODE REVIEW

**Comment by Sibam-Paul** [comment]
@Swarnendu0123 please review

**Comment by Sibam-Paul** [comment]
Can u please assign this to be

**Comment by Swarnendu0123** [comment]
you don't need to be assigned. I have already assigned the labels

**Comment by Sibam-Paul** [comment]
@Swarnendu0123 
Please assign me this pull request or else it won't count 
Prove:-
image
image

**Pull request merged**
