### PR TITLE
OOSI: Design the Link-in-bio page for click matrics

### LINKED ISSUE #5: OOSI: Design the Link-in-bio page for click matrics
# Current:

Screenshot 2024-05-13 at 11 29 56 PM

<br>

# Expected Result:

Screenshot 2024-05-14 at 12 09 57 AM
Screenshot 2024-05-14 at 12 10 04 AM

### PR DESCRIPTION
**Pull request by lazybug19**
# Fixes #5, #125

# Screenshots
image

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
- resolve the conflicts.
- remove package-lock.json file changes.

**Comment by Swarnendu0123** [comment]
Follow the structure given in pull request template.

**Comment by Swarnendu0123** [comment]
Resolve the conflicts!

**Comment by lazybug19** [comment]
Locally it says there are no conflicts and everytime I update the merged branch it shows the same files conflicting even though I have removed all commits in the conflicting files at this point.

**Comment by Swarnendu0123** [comment]
Do one thing, close this PR. Clone this repo again in another place, then create a new PR with the modified files only.

**Comment by Swarnendu0123** [comment]
Btw I asked you to remove package-lock.json. not package.json

**Pull request closed without merging**
