### PR TITLE
added the logo to navbar.tsx

### PR DESCRIPTION
**Pull request by abhay-sen**
Fixes: #21
added the logo to navbar .
image

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Decrease the logo size.

**Comment by abhay-sen** [comment]
done @Swarnendu0123

**Comment by Swarnendu0123** [comment]
Modify your old screenshot.

**Comment by Swarnendu0123** [comment]
When I asked for decreasing the size, I mean you should copy the icon in the assets folder then crop the upper and the lower white portion and attach the asset logo. I does Not mean to decrease the height in HTML.

**Comment by abhay-sen** [comment]
> When I asked for decreasing the size, I mean you should copy the icon in the assets folder then crop and remove the upper and the lower white portion and attach the asset logo not directly from the public folder. I does Not mean to decrease the height in HTML.

Okay sir

**Comment by abhay-sen** [comment]
@Swarnendu0123 done.. please check if any further changes are to be made or not

**Pull request merged**
