### PR TITLE
Profile Dropdown

### PR DESCRIPTION
**Pull request by tom-blk**
Fixes: #19
Implemented a basic profile drop-down menu that can be expanded upon in the future.

Click Matrics - Brave_001

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Attach a screenshot.

**Comment by tom-blk** [comment]
Done. Sorry, read your message on the other thread too late.

**Comment by tom-blk** [comment]
What test do you mean? All fonts bold?

**Comment by Swarnendu0123** [comment]
> What test do you mean? 

Oh sorry, I mean text. 

>  All fonts bold?

Yes, all fonts in the dropdown.

**Comment by tom-blk** [comment]
Okay, done.

Click Matrics - Brave_001

**Comment by Swarnendu0123** [comment]
Thanks for your contribution. Welcome to oxiton.

**Comment by Swarnendu0123** [comment]
Submit your reviews: https://forms.gle/81JfHd2nGXzXss5b8

**Pull request merged**
