### PR TITLE
OOSI: Design the Link-in-bio page for click matrics

### LINKED ISSUE #5: OOSI: Design the Link-in-bio page for click matrics
# Current:

Screenshot 2024-05-13 at 11 29 56 PM

<br>

# Expected Result:

Screenshot 2024-05-14 at 12 09 57 AM
Screenshot 2024-05-14 at 12 10 04 AM

### PR DESCRIPTION
**Pull request by lazybug19**
# Fixes #5

## Screenshots
image

### CODE REVIEW

**Comment by lazybug19** [comment]
@Swarnendu0123

**Comment by Swarnendu0123** [comment]
I have already reviewed, please do the modifications mentioned in this https://github.com/oxiton-foundation/click-metrics/pull/132#pullrequestreview-2094642316

**Comment by lazybug19** [comment]
No review comments are visible to me. The link says 0 reviews in total reviews section.

**Comment by Swarnendu0123** [comment]
Please attach what the GitHub is showing.

**Comment by lazybug19** [comment]
image

**Comment by Swarnendu0123** [comment]
Sorry to say, but you should learn how to use GitHub first.



I can clearly see, I have reviewed these two comments which can be accessible in https://github.com/oxiton-foundation/click-metrics/pull/132#pullrequestreview-2094642316.

**Comment by lazybug19** [comment]
hey, thank you for your kind feedback. 
Meanwhile check this github documentation [Reviewing a pr](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) since the ss you attached clearly shows your changes as pending and the documentation also states :
image

For further proof of no review requests on my side:
image
noreview

**Comment by Swarnendu0123** [comment]
Let's give it a final touch, resolve the conflicts and we are done.

**Comment by Swarnendu0123** [comment]
Thanks!

**Comment by lazybug19** [comment]
@Swarnendu0123 The merged pr resolved issue #5 which had level 4 label when assigned and even now. Do rectify the level for merged pr accordingly.

**Pull request merged**
