### PR TITLE
GSSoC: Adding light/dark mode feature #41

### PR DESCRIPTION
**Pull request by vedanshipathak**
issue no:#41
Added a toggle mode feature which can change light mode to dark mode
features added:
- toggle option in the navbar
- every time mode changed the page background color changes depending upon the mode.
Screenshot 2024-05-30 220809
Screenshot 2024-05-30 220815
Screenshot 2024-05-30 220822
Screenshot 2024-05-30 220829

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
1. I don't like the button that you are using! Change that.
2. You are using normal CSS, we are using tailwind CSS. Please convert it in tailwind.

**Comment by Swarnendu0123** [comment]
@vedanshipathak Refer to https://ui.shadcn.com/docs/dark-mode

**Comment by vedanshipathak** [comment]
Okay i will make the changes.

**Comment by GitSentinel** [comment]
@vedanshipathak Fix the merge conflicts as well.

**Pull request closed without merging**
