### PR TITLE
Link page designed with the changes suggested

### LINKED ISSUE #3: OOSI: Design the Links page for click matrics
# Current:

Screenshot 2024-05-13 at 11 29 31 PM

<br>

# Expected Results:

Screenshot 2024-05-13 at 11 56 31 PM

### PR DESCRIPTION
**Pull request by bhaavvya**
Fixes #3

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Can I get a screenshot?

**Comment by Swarnendu0123** [comment]
@krishna-singha Review the changes and test locally before merging.

**Comment by bhaavvya** [comment]
home page
image

**Comment by bhaavvya** [comment]
links page
image

**Pull request merged**
