### PR TITLE
feat: Custom qr added

### LINKED ISSUE #197: 💡[Feature]: Adding customizable QR code style
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

we can add logo center of the qr like the below img

### Use Case

new stylish QR

### Benefits

_No response_

### Add ScreenShots

image

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
### Related Issue(s)

- Fixes #197 

### Description

Describe the purpose and scope of your pull request here. Include a brief overview of the changes introduced and any relevant context that reviewers should be aware of.

### Changes Made

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your modifications.

- package.json
- qrcode.tsx
- file3

### Screenshots (if applicable)

image

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Code follows the project's style and conventions.
- [x] Code has been tested thoroughly, and all tests pass successfully.
- [ ] Documentation has been updated to reflect any relevant changes.
- [x] All new and modified code is adequately commented for clarity.
- [x] Pull request title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 review the PR , i added the feature of custom QR,

**Comment by Swarnendu0123** [comment]
Attach video

**Comment by Swarnendu0123** [comment]
Remove the package-lock.json from client

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 

https://github.com/oxiton-foundation/click-metrics/assets/125277258/a559932c-364c-498f-87c0-fb7f029db455

**Comment by Swarnendu0123** [comment]
You shouldn't make an additional route. You should continue and add the functionality to the same page.

**Comment by RamakrushnaBiswal** [comment]
Hi @Swarnendu0123 your url generator api is different, I am using a package so I face some problem to implement that is that page that's why I create an another route

**Comment by RamakrushnaBiswal** [comment]
And if you want it into the same page i can make another section for that

**Comment by RamakrushnaBiswal** [comment]
@Swarnendu0123 review the PR

**Comment by Swarnendu0123** [comment]
> Hi @Swarnendu0123 your url generator api is different, I am using a package so I face some problem to implement that is that page that's why I create an another route 

Please implement the same route, you shouldn't say that you have faced problems so you have done this. If you are getting some error, resolve that. We are building a serious product. And making an extra route is not acceptable, when there is already a route that exists. Please continue over the same route. Otherwise I have to close this PR.

**Comment by RamakrushnaBiswal** [comment]
hi @Swarnendu0123 i fixed it can you please check

**Comment by RamakrushnaBiswal** [comment]
https://github.com/oxiton-foundation/click-metrics/assets/125277258/c2ca2e24-08f6-41bc-9b16-43cf8d0a9aa3

**Comment by Swarnendu0123** [comment]
Thanks!

**Comment by Swarnendu0123** [comment]
claim your certificate: https://www.oxiton.live/dashboard

**Pull request merged**
