### PR TITLE
Modify navbar

### PR DESCRIPTION
**Pull request by root-0101**
- I have done the changes and make the navbar position sticky #36 
- As I added random text to check that sticky navbar works properly 

https://github.com/oxiton-foundation/click-metrics/assets/142779809/4afc9cdd-d28a-4887-b866-a60c4f49bc4b

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Attach video demonstration.

**Comment by root-0101** [comment]
Please check, I included the video demonstration

**Comment by Swarnendu0123** [comment]
> Please check, I included the video demonstration

the sidebar should be fixed.

**Comment by root-0101** [comment]
Ok got it, I will fix the issue soon

**Comment by root-0101** [comment]
please assign me the required levels for this PR

**Pull request merged**
