### PR TITLE
Theme added

### PR DESCRIPTION
**Pull request by Varsani2520**
@oxiton-foundation,

user click on theme button then user able to dark and light mode screen :
in light mode:
image

in dark mode:
image

check it and closed the issue #69

### CODE REVIEW

**Comment by Varsani2520** [comment]
Hey @oxiton-foundation ,
add the label

**Comment by Varsani2520** [comment]
Hey @oxiton-foundation,
add the label and merged it

**Comment by Varsani2520** [comment]
Hey @Swarnendu0123 ,why you closed this issue ?

**Comment by Varsani2520** [comment]
i will complaint you in gssoc

**Comment by Swarnendu0123** [comment]
We are not accepting this type of PR. You have done unnecessary changes that are not required. We appreciate your enthusiasm, but we can't accept this type of change,

1. We are using `radix-ui`, did you ask the maintainers before installing `mui`?

2. Look at your changes, you have changed>1000 lines, did you have a proper explanation for it?

We are trying to build something serious, beginners are welcome but we still can't afford this type of activity.

Thanks!

**Comment by Varsani2520** [comment]
also anyone admin not tell me about not use mui ....
if you said then i create using radix ui

**Comment by Varsani2520** [comment]
if you assigned me then claerly  told about ,not use external package

**Comment by rahulpoonia29** [comment]
Please check the repo before opening a PR. Theme can be implemented in plain tailwind too. Implementing it in Radix would be appreciated because we are already using it.

**Comment by rahulpoonia29** [comment]
@Varsani2520 Refer to this https://ui.shadcn.com/docs/dark-mode

**Comment by Varsani2520** [comment]
in link as it is like mui ,

**Comment by Swarnendu0123** [comment]
We are trying to build the same thing in #96

**Pull request closed without merging**
