### PR TITLE
updated backend for the project

### LINKED ISSUE #46: GSsoC: Shorten URLs is not working
Even if we are trying to generate the Shorten version of the URL it is not responding anything so i will fix the bug to respond in such a way that it can provide the shortest version of the URL
Screenshot 2024-05-28 115906

### PR DESCRIPTION
**Pull request by GOKULGSECE**
Issue Fixed #46
Screenshot 2024-06-04 121702
I have updated the backend of the project as it can able to generate the Shortened Version of the URL's which has been provided by the user with the use of a node package manager called ShortId which can generate the shortned link upto 10 characters

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
You haven't followed the PR description structure.

**Comment by Swarnendu0123** [comment]
How could I understand what you are trying to do here?

**Comment by GOKULGSECE** [comment]
Sorry for the actions done by me so i have edited the PR please go through to it Thank You..

**Comment by Swarnendu0123** [comment]
Remove package-lock.json from both server and client and push a commit.

**Comment by GOKULGSECE** [comment]
Okee

**Pull request closed without merging**
