### PR TITLE
Feature: fixed the search bar effect for mobile screen

### LINKED ISSUE #172: GSSoC : SEARCH Not functional on Mobile screen
### Description

The search bar is not functional on mobile screen. It got overlapped by the menu icon

image

### Changes You need to make
I will implement a search bar to expand on clicking on search icon else stay in the small area.

- file1
- file2
- file3

### Screenshots

Attach screenshots or Videos demonstrating the visual changes introduced by your pull request. This helps reviewers understand the user interface modifications more effectively.

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Gone through the [rules and guidelines](https://github.com/oxiton-foundation/click-metrics/issues/24) of the project.
- [x] When you are creating PR, your PR should title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.
- [x] Attached OSSI or GSSoC in the heading of the Issue.
- [x] I have checked this issue is not already covered in another issue.

### Expected Time to Complete

1 Day

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

### PR DESCRIPTION
**Pull request by Utsavladia**
### Related Issue(s)

- Fixes #172 

### Description

The search bar is made clickable for the mobile screen where it comes as overlap efffect on the navbar on clicking the search icon and enable the user to use the search bar on mobile screen as well.

### Changes Made

Provide a detailed list of the changes made in this pull request. Include specific files, components, or functionalities affected by your modifications.

modifies the <Search/> component 

### Screenshots (if applicable)

https://github.com/oxiton-foundation/click-metrics/assets/124615886/8affea7e-c72a-4ac3-8c8b-e64d3383eef1

Attach screenshots or Videos demonstrating the visual changes introduced by your pull request. This helps reviewers understand the user interface modifications more effectively.

### Checklist

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] Code follows the project's style and conventions.
- [x] Code has been tested thoroughly, and all tests pass successfully.
- [x] Documentation has been updated to reflect any relevant changes.
- [x] All new and modified code is adequately commented for clarity.
- [x] Pull request title follows the specified format: [Feature/Enhancement/Bug Fix]: Brief description of the change.

### Additional Notes

Add any additional information, concerns, or considerations that may be relevant to your pull request. This could include performance implications, future enhancements, or potential risks associated with the changes.

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Remove the package.json from client

**Comment by Swarnendu0123** [comment]
Also can you add some margin at the right side also, because it is touching the screen.

**Comment by Utsavladia** [comment]
@Swarnendu0123  
Sure, I Changed both.

**Comment by Swarnendu0123** [comment]
Please attach an updated video.

**Comment by Utsavladia** [comment]
@Swarnendu0123  
https://github.com/oxiton-foundation/click-metrics/assets/124615886/b71f5ee1-9e0b-47a5-a6ae-5d1774d2c771

**Comment by Swarnendu0123** [comment]
Thanks!

**Pull request merged**
