### PR TITLE
GSSOC : Added CODE_OF_CONDUCT.md

### LINKED ISSUE #17: GSSoC: Add Code of Conduct.md
It is important for our community to have a clear and concise code of conduct to ensure a welcoming and inclusive environment for all contributors. A Code of Conduct sets the expectation for behavior and outlines the steps for reporting and addressing unacceptable behavior. This can greatly enhance the community experience and maintain a respectful and collaborative atmosphere.
I want to add Code_of_conduct.md, please assign me this issue.

### PR DESCRIPTION
**Pull request by Santhosh-Siddhardha**
Added Pledge Section
Added Standards Section
Added Enforcement Responsibilities Section
Added Scope Section
Added Enforcement Section
Added Enforcement Guidelines Section

Closes #17

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Thanks for your contribution.

**Comment by Swarnendu0123** [comment]
Sign up to [www.oxiton.live/](https://www.oxiton.live/) to track your pull request.

**Comment by Swarnendu0123** [comment]
Is it okey now?

**Comment by Santhosh-Siddhardha** [comment]
Yeah, Thank you

**Comment by Swarnendu0123** [comment]
Submit your reviews: https://forms.gle/81JfHd2nGXzXss5b8

**Comment by Santhosh-Siddhardha** [comment]
@Swarnendu0123 Please assign this PR to me.

**Pull request merged**
