### PR TITLE
Analytics Page UI

### PR DESCRIPTION
**Pull request by Prime351585**
Improved UI of Analytics Page
Fixed the profile bar issue
Now Navbar always remains on top over the charts.

this is the final image for now, if want any changes notify me.
image

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Why your Pull request showing > 4000 lines of changes?

**Comment by Prime351585** [comment]
it was a package-lock.json file with 4682 lines of code which automatically gets created when I run "npm i", I can't do anything about it,i have only changed around lines of code.

**Comment by Prime351585** [comment]
I've closed this PR for now I'll open another one with less lines of updates tomorrow.

**Comment by Swarnendu0123** [comment]
> it was a package-lock.json file with 4682 lines of code which automatically gets created when I run "npm i", I can't do anything about it,i have only changed around 202 lines of code.

After installing the dependencies you can remove the lock file. It will not create any issues.

**Comment by Prime351585** [comment]
okay I've done the same and created a new PR, check #128

**Pull request closed without merging**
